version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.4

jobs:
  validate:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
          name: Restore NPM Cache
      - run:
          command: npm install
          name: install npm dependencies
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          name: Save NPM Cache
          paths:
            - ~/.npm
      - run:
          command: ./scripts/validate.sh
          name: Validate Renovate config presets

workflows:
  version: 2
  validate:
    jobs:
      - validate:
          requires:
            - shellcheck/check
      - shellcheck/check:
          pre-steps:
            - run:
                command: |
                  apk add --no-progress --update-cache git openssh-client
                name: Install Git and SSH CLient
