name: Validate renovate config

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version-file: ".nvmrc"


    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version-file }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version-file }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      - name: Validate renovate config
        run: npx --package renovate -c 'renovate-config-validator'
